#!/bin/sh
/etc/init.d/adh-direct enable >/dev/null 2>&1 || true
/etc/init.d/adh-proxy enable >/dev/null 2>&1 || true
/etc/init.d/adh-direct start >/dev/null 2>&1 || true
/etc/init.d/adh-proxy start >/dev/null 2>&1 || true
exit 0
