#!/usr/bin/env python3
"""Sync selected OpenWrt packages from upstream Git repositories."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources.json"
SUMMARY = ROOT / "SYNCED_SOURCES.md"


def run(cmd: list[str], cwd: Path | None = None) -> str:
    print("+", " ".join(cmd), flush=True)
    result = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    if result.stdout:
        print(result.stdout, end="")
    return result.stdout.strip()


def clone_source(source: dict, workdir: Path) -> dict:
    name = source["name"]
    repo = source["repo"]
    branch = source.get("branch")
    dest_rel = Path(source["path"])
    dest = ROOT / dest_rel
    clone_dir = workdir / name

    cmd = ["git", "clone", "--depth", "1"]
    if branch:
        cmd += ["-b", branch]
    cmd += [repo, str(clone_dir)]
    run(cmd)

    commit = run(["git", "rev-parse", "HEAD"], cwd=clone_dir)
    actual_branch = branch or run(["git", "branch", "--show-current"], cwd=clone_dir) or "default"

    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        clone_dir,
        dest,
        ignore=shutil.ignore_patterns(".git", ".github/workflows", "*.md~"),
    )

    return {
        "name": name,
        "path": str(dest_rel),
        "repo": repo,
        "branch": actual_branch,
        "commit": commit,
        "description": source.get("description", ""),
    }


def write_summary(records: list[dict]) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# Synced Sources",
        "",
        f"Last sync: `{now}`",
        "",
        "| Package | Path | Branch | Commit | Upstream |",
        "|---------|------|--------|--------|----------|",
    ]
    for item in records:
        short = item["commit"][:12]
        lines.append(
            f"| {item['name']} | `{item['path']}` | `{item['branch']}` | `{short}` | {item['repo']} |"
        )
    lines.append("")
    lines.append("> This file is generated by `scripts/sync-packages.py`.")
    lines.append("")
    SUMMARY.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    sources = json.loads(SOURCES.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory(prefix="openwrt-packages-") as tmp:
        records = [clone_source(source, Path(tmp)) for source in sources]
    write_summary(records)
    print("Sync complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
