#!/usr/bin/env python3
"""Sync selected OpenWrt packages from upstream Git repositories.

The sync is a plain copy of each upstream tree, with one addition: files under
``overrides/`` are copied over the synced result afterwards.  Upstream packages
this firmware has to diverge from (Lucky 3.x no longer ships from GitHub at all,
see ``overrides/README.md``) would otherwise be reverted on every run, and a
revert here silently changes what the firmware builds.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "sources.json"
SUMMARY = ROOT / "SYNCED_SOURCES.md"
OVERRIDES = ROOT / "overrides"


class SyncError(RuntimeError):
    pass


def run(cmd: list[str], cwd: Path | None = None) -> str:
    print("+", " ".join(cmd), flush=True)
    result = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    if result.stdout:
        print(result.stdout, end="")
    return result.stdout.strip()


def clone_source(source: dict, workdir: Path) -> dict:
    name = source["name"]
    repo = source["repo"]
    branch = source.get("branch")
    dest_rel = Path(source["path"])
    dest = ROOT / dest_rel
    clone_dir = workdir / name

    cmd = ["git", "clone", "--depth", "1"]
    if branch:
        cmd += ["-b", branch]
    cmd += [repo, str(clone_dir)]
    run(cmd)

    commit = run(["git", "rev-parse", "HEAD"], cwd=clone_dir)
    actual_branch = branch or run(["git", "branch", "--show-current"], cwd=clone_dir) or "default"

    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        clone_dir,
        dest,
        ignore=shutil.ignore_patterns(".git", ".github/workflows", "*.md~"),
    )

    return {
        "name": name,
        "path": str(dest_rel),
        "repo": repo,
        "branch": actual_branch,
        "commit": commit,
        "description": source.get("description", ""),
    }


def apply_overrides(synced: set[str]) -> list[str]:
    """Copy ``overrides/`` over the freshly synced trees.

    Returns the repository-relative paths that were replaced.  Only the package
    directories are walked: files directly under ``overrides/`` (the README) are
    documentation.  Each override has to live inside a package directory the
    sync just produced -- a typo or a stale path would otherwise add a directory
    upstream never had, and the firmware would quietly build the unpatched file.
    """
    if not OVERRIDES.is_dir():
        return []

    applied: list[str] = []
    for package_dir in sorted(entry for entry in OVERRIDES.iterdir() if entry.is_dir()):
        if package_dir.name not in synced:
            raise SyncError(
                f"overrides/{package_dir.name}/ does not belong to a synced package "
                f"(expected one of: {', '.join(sorted(synced))})"
            )
        for source in sorted(package_dir.rglob("*")):
            if source.is_dir():
                continue
            relative = source.relative_to(OVERRIDES)
            destination = ROOT / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            applied.append(str(relative))
            print(f"+ override {relative}")
    return applied


def write_summary(records: list[dict], applied: list[str]) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines = [
        "# Synced Sources",
        "",
        f"Last sync: `{now}`",
        "",
        "| Package | Path | Branch | Commit | Upstream |",
        "|---------|------|--------|--------|----------|",
    ]
    for item in records:
        short = item["commit"][:12]
        lines.append(
            f"| {item['name']} | `{item['path']}` | `{item['branch']}` | `{short}` | {item['repo']} |"
        )
    lines.append("")
    if applied:
        lines.append("Overridden after sync (see `overrides/README.md`):")
        lines.append("")
        for path in applied:
            lines.append(f"- `{path}`")
        lines.append("")
    lines.append("> This file is generated by `scripts/sync-packages.py`.")
    lines.append("")
    SUMMARY.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    sources = json.loads(SOURCES.read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory(prefix="openwrt-packages-") as tmp:
        records = [clone_source(source, Path(tmp)) for source in sources]
    applied = apply_overrides({item["path"] for item in records})
    write_summary(records, applied)
    print("Sync complete.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SyncError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
