include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for the Guangxi Mobile IPTV scanner
LUCI_DEPENDS:=+gxmobile-scan +rpcd-mod-ucode +ucode-mod-fs +ucode-mod-uci
LUCI_PKGARCH:=all
PKG_VERSION:=1.2.0
PKG_RELEASE:=2
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
